cc_library(
    name = 'path',
    srcs = [
        'path.cpp',
    ],
    deps = '//toft/base/string:string',
)


cc_test(
    name = 'path_test',
    srcs = ['path_test.cpp'],
    deps = [':path']
)

