cc_library(
    name = 'domain_util',
    srcs = ['domain_util.cpp',],
    deps = ['//toft/net/uri:url']
)

cc_test(
    name = 'domain_util_test',
    srcs = ['domain_util_test.cpp',],
    deps = [
        ':domain_util',
    ]
)