cc_library(
    name = 'registry_controlled_domain',
    srcs = ['registry_controlled_domain.cc',],
    deps = ['//toft/net/uri:url']
)

cc_test(
    name = 'registry_controlled_domain_unittest',
    srcs = ['registry_controlled_domain_unittest.cc',],
    deps = [
        ':registry_controlled_domain',
    ]
)