cc_library(
    name = 'hash',
    srcs = 'hash.cpp',
    deps = ['//thirdparty/stringencoders:stringencoders'],
)

cc_test(
    name = 'hash_unittest',
    srcs = 'hash_unittest.cpp',
    deps = [':hash'],
)
