# Copyright 2012. All Rights Reserved.
# Author: yeshunping@gmail.com (Shunping Ye)
#
# Description:
#   TODO(shunpingye): describe this package.

cc_test(name = 'lru_cache_test',
        srcs = ['lru_cache_test.cc', ],
        deps = [
                '//toft/system/threading:threading',
               ],
        )

cc_test(name = 'threadsafe_lru_cache_test',
        srcs = ['threadsafe_lru_cache_test.cc', ],
        deps = [
                '//toft/system/threading:threading',
               ],
        )
