// This file was GENERATED by command:
//     pump.py print.h.pump
// DO NOT EDIT BY HAND!!!

// Copyright (c) 2013, The TOFT Authors.
// All rights reserved.
//
// Author: CHEN Feng <chen3feng@gmail.com>
// Created: 2013-02-07

#ifndef TOFT_BASE_STRING_FORMAT_PRINT_H
#define TOFT_BASE_STRING_FORMAT_PRINT_H
#pragma once

#include <string>

#include "toft/base/string/format/print_arg.h"

namespace toft {

//////////////////////////////////////////////////////////////////////////////
// 0 arg

int StringPrintTo(std::string* out, const char* format);
int StringPrintAppend(std::string* out, const char* format);
std::string StringPrint(const char* format);

//////////////////////////////////////////////////////////////////////////////
// 1 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1);

//////////////////////////////////////////////////////////////////////////////
// 2 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2);

//////////////////////////////////////////////////////////////////////////////
// 3 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3);

//////////////////////////////////////////////////////////////////////////////
// 4 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3,
                  const FormatPrintArg& arg4);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3,
                      const FormatPrintArg& arg4);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3,
                        const FormatPrintArg& arg4);

//////////////////////////////////////////////////////////////////////////////
// 5 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3,
                  const FormatPrintArg& arg4,
                  const FormatPrintArg& arg5);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3,
                      const FormatPrintArg& arg4,
                      const FormatPrintArg& arg5);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3,
                        const FormatPrintArg& arg4,
                        const FormatPrintArg& arg5);

//////////////////////////////////////////////////////////////////////////////
// 6 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3,
                  const FormatPrintArg& arg4,
                  const FormatPrintArg& arg5,
                  const FormatPrintArg& arg6);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3,
                      const FormatPrintArg& arg4,
                      const FormatPrintArg& arg5,
                      const FormatPrintArg& arg6);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3,
                        const FormatPrintArg& arg4,
                        const FormatPrintArg& arg5,
                        const FormatPrintArg& arg6);

//////////////////////////////////////////////////////////////////////////////
// 7 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3,
                  const FormatPrintArg& arg4,
                  const FormatPrintArg& arg5,
                  const FormatPrintArg& arg6,
                  const FormatPrintArg& arg7);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3,
                      const FormatPrintArg& arg4,
                      const FormatPrintArg& arg5,
                      const FormatPrintArg& arg6,
                      const FormatPrintArg& arg7);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3,
                        const FormatPrintArg& arg4,
                        const FormatPrintArg& arg5,
                        const FormatPrintArg& arg6,
                        const FormatPrintArg& arg7);

//////////////////////////////////////////////////////////////////////////////
// 8 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3,
                  const FormatPrintArg& arg4,
                  const FormatPrintArg& arg5,
                  const FormatPrintArg& arg6,
                  const FormatPrintArg& arg7,
                  const FormatPrintArg& arg8);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3,
                      const FormatPrintArg& arg4,
                      const FormatPrintArg& arg5,
                      const FormatPrintArg& arg6,
                      const FormatPrintArg& arg7,
                      const FormatPrintArg& arg8);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3,
                        const FormatPrintArg& arg4,
                        const FormatPrintArg& arg5,
                        const FormatPrintArg& arg6,
                        const FormatPrintArg& arg7,
                        const FormatPrintArg& arg8);

//////////////////////////////////////////////////////////////////////////////
// 9 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3,
                  const FormatPrintArg& arg4,
                  const FormatPrintArg& arg5,
                  const FormatPrintArg& arg6,
                  const FormatPrintArg& arg7,
                  const FormatPrintArg& arg8,
                  const FormatPrintArg& arg9);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3,
                      const FormatPrintArg& arg4,
                      const FormatPrintArg& arg5,
                      const FormatPrintArg& arg6,
                      const FormatPrintArg& arg7,
                      const FormatPrintArg& arg8,
                      const FormatPrintArg& arg9);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3,
                        const FormatPrintArg& arg4,
                        const FormatPrintArg& arg5,
                        const FormatPrintArg& arg6,
                        const FormatPrintArg& arg7,
                        const FormatPrintArg& arg8,
                        const FormatPrintArg& arg9);

//////////////////////////////////////////////////////////////////////////////
// 10 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3,
                  const FormatPrintArg& arg4,
                  const FormatPrintArg& arg5,
                  const FormatPrintArg& arg6,
                  const FormatPrintArg& arg7,
                  const FormatPrintArg& arg8,
                  const FormatPrintArg& arg9,
                  const FormatPrintArg& arg10);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3,
                      const FormatPrintArg& arg4,
                      const FormatPrintArg& arg5,
                      const FormatPrintArg& arg6,
                      const FormatPrintArg& arg7,
                      const FormatPrintArg& arg8,
                      const FormatPrintArg& arg9,
                      const FormatPrintArg& arg10);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3,
                        const FormatPrintArg& arg4,
                        const FormatPrintArg& arg5,
                        const FormatPrintArg& arg6,
                        const FormatPrintArg& arg7,
                        const FormatPrintArg& arg8,
                        const FormatPrintArg& arg9,
                        const FormatPrintArg& arg10);

//////////////////////////////////////////////////////////////////////////////
// 11 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3,
                  const FormatPrintArg& arg4,
                  const FormatPrintArg& arg5,
                  const FormatPrintArg& arg6,
                  const FormatPrintArg& arg7,
                  const FormatPrintArg& arg8,
                  const FormatPrintArg& arg9,
                  const FormatPrintArg& arg10,
                  const FormatPrintArg& arg11);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3,
                      const FormatPrintArg& arg4,
                      const FormatPrintArg& arg5,
                      const FormatPrintArg& arg6,
                      const FormatPrintArg& arg7,
                      const FormatPrintArg& arg8,
                      const FormatPrintArg& arg9,
                      const FormatPrintArg& arg10,
                      const FormatPrintArg& arg11);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3,
                        const FormatPrintArg& arg4,
                        const FormatPrintArg& arg5,
                        const FormatPrintArg& arg6,
                        const FormatPrintArg& arg7,
                        const FormatPrintArg& arg8,
                        const FormatPrintArg& arg9,
                        const FormatPrintArg& arg10,
                        const FormatPrintArg& arg11);

//////////////////////////////////////////////////////////////////////////////
// 12 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3,
                  const FormatPrintArg& arg4,
                  const FormatPrintArg& arg5,
                  const FormatPrintArg& arg6,
                  const FormatPrintArg& arg7,
                  const FormatPrintArg& arg8,
                  const FormatPrintArg& arg9,
                  const FormatPrintArg& arg10,
                  const FormatPrintArg& arg11,
                  const FormatPrintArg& arg12);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3,
                      const FormatPrintArg& arg4,
                      const FormatPrintArg& arg5,
                      const FormatPrintArg& arg6,
                      const FormatPrintArg& arg7,
                      const FormatPrintArg& arg8,
                      const FormatPrintArg& arg9,
                      const FormatPrintArg& arg10,
                      const FormatPrintArg& arg11,
                      const FormatPrintArg& arg12);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3,
                        const FormatPrintArg& arg4,
                        const FormatPrintArg& arg5,
                        const FormatPrintArg& arg6,
                        const FormatPrintArg& arg7,
                        const FormatPrintArg& arg8,
                        const FormatPrintArg& arg9,
                        const FormatPrintArg& arg10,
                        const FormatPrintArg& arg11,
                        const FormatPrintArg& arg12);

//////////////////////////////////////////////////////////////////////////////
// 13 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3,
                  const FormatPrintArg& arg4,
                  const FormatPrintArg& arg5,
                  const FormatPrintArg& arg6,
                  const FormatPrintArg& arg7,
                  const FormatPrintArg& arg8,
                  const FormatPrintArg& arg9,
                  const FormatPrintArg& arg10,
                  const FormatPrintArg& arg11,
                  const FormatPrintArg& arg12,
                  const FormatPrintArg& arg13);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3,
                      const FormatPrintArg& arg4,
                      const FormatPrintArg& arg5,
                      const FormatPrintArg& arg6,
                      const FormatPrintArg& arg7,
                      const FormatPrintArg& arg8,
                      const FormatPrintArg& arg9,
                      const FormatPrintArg& arg10,
                      const FormatPrintArg& arg11,
                      const FormatPrintArg& arg12,
                      const FormatPrintArg& arg13);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3,
                        const FormatPrintArg& arg4,
                        const FormatPrintArg& arg5,
                        const FormatPrintArg& arg6,
                        const FormatPrintArg& arg7,
                        const FormatPrintArg& arg8,
                        const FormatPrintArg& arg9,
                        const FormatPrintArg& arg10,
                        const FormatPrintArg& arg11,
                        const FormatPrintArg& arg12,
                        const FormatPrintArg& arg13);

//////////////////////////////////////////////////////////////////////////////
// 14 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3,
                  const FormatPrintArg& arg4,
                  const FormatPrintArg& arg5,
                  const FormatPrintArg& arg6,
                  const FormatPrintArg& arg7,
                  const FormatPrintArg& arg8,
                  const FormatPrintArg& arg9,
                  const FormatPrintArg& arg10,
                  const FormatPrintArg& arg11,
                  const FormatPrintArg& arg12,
                  const FormatPrintArg& arg13,
                  const FormatPrintArg& arg14);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3,
                      const FormatPrintArg& arg4,
                      const FormatPrintArg& arg5,
                      const FormatPrintArg& arg6,
                      const FormatPrintArg& arg7,
                      const FormatPrintArg& arg8,
                      const FormatPrintArg& arg9,
                      const FormatPrintArg& arg10,
                      const FormatPrintArg& arg11,
                      const FormatPrintArg& arg12,
                      const FormatPrintArg& arg13,
                      const FormatPrintArg& arg14);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3,
                        const FormatPrintArg& arg4,
                        const FormatPrintArg& arg5,
                        const FormatPrintArg& arg6,
                        const FormatPrintArg& arg7,
                        const FormatPrintArg& arg8,
                        const FormatPrintArg& arg9,
                        const FormatPrintArg& arg10,
                        const FormatPrintArg& arg11,
                        const FormatPrintArg& arg12,
                        const FormatPrintArg& arg13,
                        const FormatPrintArg& arg14);

//////////////////////////////////////////////////////////////////////////////
// 15 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3,
                  const FormatPrintArg& arg4,
                  const FormatPrintArg& arg5,
                  const FormatPrintArg& arg6,
                  const FormatPrintArg& arg7,
                  const FormatPrintArg& arg8,
                  const FormatPrintArg& arg9,
                  const FormatPrintArg& arg10,
                  const FormatPrintArg& arg11,
                  const FormatPrintArg& arg12,
                  const FormatPrintArg& arg13,
                  const FormatPrintArg& arg14,
                  const FormatPrintArg& arg15);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3,
                      const FormatPrintArg& arg4,
                      const FormatPrintArg& arg5,
                      const FormatPrintArg& arg6,
                      const FormatPrintArg& arg7,
                      const FormatPrintArg& arg8,
                      const FormatPrintArg& arg9,
                      const FormatPrintArg& arg10,
                      const FormatPrintArg& arg11,
                      const FormatPrintArg& arg12,
                      const FormatPrintArg& arg13,
                      const FormatPrintArg& arg14,
                      const FormatPrintArg& arg15);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3,
                        const FormatPrintArg& arg4,
                        const FormatPrintArg& arg5,
                        const FormatPrintArg& arg6,
                        const FormatPrintArg& arg7,
                        const FormatPrintArg& arg8,
                        const FormatPrintArg& arg9,
                        const FormatPrintArg& arg10,
                        const FormatPrintArg& arg11,
                        const FormatPrintArg& arg12,
                        const FormatPrintArg& arg13,
                        const FormatPrintArg& arg14,
                        const FormatPrintArg& arg15);

//////////////////////////////////////////////////////////////////////////////
// 16 args

int StringPrintTo(std::string* out, const char* format,
                  const FormatPrintArg& arg1,
                  const FormatPrintArg& arg2,
                  const FormatPrintArg& arg3,
                  const FormatPrintArg& arg4,
                  const FormatPrintArg& arg5,
                  const FormatPrintArg& arg6,
                  const FormatPrintArg& arg7,
                  const FormatPrintArg& arg8,
                  const FormatPrintArg& arg9,
                  const FormatPrintArg& arg10,
                  const FormatPrintArg& arg11,
                  const FormatPrintArg& arg12,
                  const FormatPrintArg& arg13,
                  const FormatPrintArg& arg14,
                  const FormatPrintArg& arg15,
                  const FormatPrintArg& arg16);

int StringPrintAppend(std::string* out, const char* format,
                      const FormatPrintArg& arg1,
                      const FormatPrintArg& arg2,
                      const FormatPrintArg& arg3,
                      const FormatPrintArg& arg4,
                      const FormatPrintArg& arg5,
                      const FormatPrintArg& arg6,
                      const FormatPrintArg& arg7,
                      const FormatPrintArg& arg8,
                      const FormatPrintArg& arg9,
                      const FormatPrintArg& arg10,
                      const FormatPrintArg& arg11,
                      const FormatPrintArg& arg12,
                      const FormatPrintArg& arg13,
                      const FormatPrintArg& arg14,
                      const FormatPrintArg& arg15,
                      const FormatPrintArg& arg16);

std::string StringPrint(const char* format,
                        const FormatPrintArg& arg1,
                        const FormatPrintArg& arg2,
                        const FormatPrintArg& arg3,
                        const FormatPrintArg& arg4,
                        const FormatPrintArg& arg5,
                        const FormatPrintArg& arg6,
                        const FormatPrintArg& arg7,
                        const FormatPrintArg& arg8,
                        const FormatPrintArg& arg9,
                        const FormatPrintArg& arg10,
                        const FormatPrintArg& arg11,
                        const FormatPrintArg& arg12,
                        const FormatPrintArg& arg13,
                        const FormatPrintArg& arg14,
                        const FormatPrintArg& arg15,
                        const FormatPrintArg& arg16);

} // namespace toft

#endif // TOFT_BASE_STRING_FORMAT_PRINT_H
