// This file was GENERATED by command:
//     pump.py scan.h.pump
// DO NOT EDIT BY HAND!!!

// Copyright (c) 2013, The TOFT Authors.
// All rights reserved.
//
// Author: CHEN Feng <chen3feng@gmail.com>
// Created: 2013-02-06

#ifndef TOFT_BASE_STRING_FORMAT_SCAN_H
#define TOFT_BASE_STRING_FORMAT_SCAN_H

#include <string>

#include "toft/base/string/format/scan_arg.h"

// GLOBAL_NOLINT(build/include_what_you_use)

namespace toft {

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13,
    const FormatScanArg& arg14
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13,
    const FormatScanArg& arg14
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13,
    const FormatScanArg& arg14,
    const FormatScanArg& arg15
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13,
    const FormatScanArg& arg14,
    const FormatScanArg& arg15
);

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13,
    const FormatScanArg& arg14,
    const FormatScanArg& arg15,
    const FormatScanArg& arg16
);

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13,
    const FormatScanArg& arg14,
    const FormatScanArg& arg15,
    const FormatScanArg& arg16
);

} // namespace toft

#endif // TOFT_BASE_STRING_FORMAT_SCAN_H
