// This file was GENERATED by command:
//     pump.py scan.cpp.pump
// DO NOT EDIT BY HAND!!!

// Copyright (c) 2013, The TOFT Authors.
// All rights reserved.
//
// Author: CHEN Feng <chen3feng@gmail.com>
// Created: 2013-02-06

#include "toft/base/string/format/scan.h"

#include "toft/base/string/format/vscan.h"

namespace toft {

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1
)
{
    const FormatScanArg* args[] = {
        &arg1,
    };
    return StringVScan(string, format, args, 1);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1
)
{
    return StringScan(string.c_str(), format, arg1);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
    };
    return StringVScan(string, format, args, 2);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2
)
{
    return StringScan(string.c_str(), format, arg1, arg2);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
    };
    return StringVScan(string, format, args, 3);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
        &arg4,
    };
    return StringVScan(string, format, args, 4);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3, arg4);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
        &arg4,
        &arg5,
    };
    return StringVScan(string, format, args, 5);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3, arg4, arg5);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
        &arg4,
        &arg5,
        &arg6,
    };
    return StringVScan(string, format, args, 6);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3, arg4, arg5,
        arg6);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
        &arg4,
        &arg5,
        &arg6,
        &arg7,
    };
    return StringVScan(string, format, args, 7);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3, arg4, arg5,
        arg6, arg7);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
        &arg4,
        &arg5,
        &arg6,
        &arg7,
        &arg8,
    };
    return StringVScan(string, format, args, 8);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3, arg4, arg5,
        arg6, arg7, arg8);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
        &arg4,
        &arg5,
        &arg6,
        &arg7,
        &arg8,
        &arg9,
    };
    return StringVScan(string, format, args, 9);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3, arg4, arg5,
        arg6, arg7, arg8, arg9);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
        &arg4,
        &arg5,
        &arg6,
        &arg7,
        &arg8,
        &arg9,
        &arg10,
    };
    return StringVScan(string, format, args, 10);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3, arg4, arg5,
        arg6, arg7, arg8, arg9, arg10);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
        &arg4,
        &arg5,
        &arg6,
        &arg7,
        &arg8,
        &arg9,
        &arg10,
        &arg11,
    };
    return StringVScan(string, format, args, 11);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3, arg4, arg5,
        arg6, arg7, arg8, arg9, arg10, arg11);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
        &arg4,
        &arg5,
        &arg6,
        &arg7,
        &arg8,
        &arg9,
        &arg10,
        &arg11,
        &arg12,
    };
    return StringVScan(string, format, args, 12);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3, arg4, arg5,
        arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
        &arg4,
        &arg5,
        &arg6,
        &arg7,
        &arg8,
        &arg9,
        &arg10,
        &arg11,
        &arg12,
        &arg13,
    };
    return StringVScan(string, format, args, 13);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3, arg4, arg5,
        arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13,
    const FormatScanArg& arg14
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
        &arg4,
        &arg5,
        &arg6,
        &arg7,
        &arg8,
        &arg9,
        &arg10,
        &arg11,
        &arg12,
        &arg13,
        &arg14,
    };
    return StringVScan(string, format, args, 14);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13,
    const FormatScanArg& arg14
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3, arg4, arg5,
        arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13,
    const FormatScanArg& arg14,
    const FormatScanArg& arg15
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
        &arg4,
        &arg5,
        &arg6,
        &arg7,
        &arg8,
        &arg9,
        &arg10,
        &arg11,
        &arg12,
        &arg13,
        &arg14,
        &arg15,
    };
    return StringVScan(string, format, args, 15);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13,
    const FormatScanArg& arg14,
    const FormatScanArg& arg15
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3, arg4, arg5,
        arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
}

int StringScan(
    const char* string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13,
    const FormatScanArg& arg14,
    const FormatScanArg& arg15,
    const FormatScanArg& arg16
)
{
    const FormatScanArg* args[] = {
        &arg1,
        &arg2,
        &arg3,
        &arg4,
        &arg5,
        &arg6,
        &arg7,
        &arg8,
        &arg9,
        &arg10,
        &arg11,
        &arg12,
        &arg13,
        &arg14,
        &arg15,
        &arg16,
    };
    return StringVScan(string, format, args, 16);
}

int StringScan(
    const std::string& string, const char* format,
    const FormatScanArg& arg1,
    const FormatScanArg& arg2,
    const FormatScanArg& arg3,
    const FormatScanArg& arg4,
    const FormatScanArg& arg5,
    const FormatScanArg& arg6,
    const FormatScanArg& arg7,
    const FormatScanArg& arg8,
    const FormatScanArg& arg9,
    const FormatScanArg& arg10,
    const FormatScanArg& arg11,
    const FormatScanArg& arg12,
    const FormatScanArg& arg13,
    const FormatScanArg& arg14,
    const FormatScanArg& arg15,
    const FormatScanArg& arg16
)
{
    return StringScan(string.c_str(), format, arg1, arg2, arg3, arg4, arg5,
        arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15,
        arg16);
}

} // namespace toft
